### ISSUE TITLE
Interweave fails to work serverside

### ISSUE THREAD

**Issue by Noiwex** [milesj/interweave#14]
How to reproduce:

Step 1. Try to render some component that uses Interweave in nodejs.
Step 2:
```
ReferenceError: document is not defined
    at Parser.createDocument (/Users/nx/Development/web/node_modules/interweave/lib/Parser.js:211:17)
    at new Parser (/Users/nx/Development/web/node_modules/interweave/lib/Parser.js:79:21)
    at Interweave.parseMarkup (/Users/nx/Development/web/node_modules/interweave/lib/Interweave.js:108:16)
    at Interweave.render (/Users/nx/Development/web/node_modules/interweave/lib/Interweave.js:138:14)
    at /Users/nx/Development/web/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
```

**Comment by milesj** [comment]
Interweave requires a DOM to render as it uses the DOM itself to parse HTML.

**Comment by Noiwex** [comment]
In the day of server-side rendering it's highly inconvenient.

**Comment by milesj** [comment]
I don't see this ever changing. At most you can polyfill `DOMImplementation`.

* https://github.com/milesj/interweave/blob/master/src/Parser.js#L245
* https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument

**Comment by milesj** [comment]
I won't be removing the DOM, but you can SSR via JSDOM. Added some tests and some quick documentation. 

https://github.com/milesj/interweave#server-side-rendering

**Comment by Noiwex** [comment]
👌

**Comment by bryndyment** [comment]
Updated link: https://milesj.gitbook.io/interweave/ssr
