### ISSUE TITLE
email matcher fails when email address is in a question

### ISSUE THREAD

**Issue by michaelkantor** [milesj/interweave#201]
Email matcher handles email addresses that end in question marks as follows:

INPUT: "Can you please send an email to mkantor@gmail.com?"

OUTPUT: "can you email {{{url0}}}mkantor@gmail.com?{{{/url0}}}"

PROBLEM: that question mark is doing something to the regex, which matches correctly without it.

Note: I git cloned the repo and tried to take a closer look, but was unable to get any unit tests running. The rest of this message details problems related to dev setup rather than email matcher:

```
npm test -- packages/autolink/tests/EmailMatcher.test.ts
```
returns
```
> interweave-root@0.0.0 pretest /Users/michaelkantor/Documents/interweave
> yarn run type

yarn run v1.22.4
$ beemo typescript --reference-workspaces --build
[1/2] CONFIG Creating config files
[2/2] DRIVER Running TypeScript v4.4.3 driver (failed)

packages/ssr/src/index.ts(138,10): error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

Failed to execute pipeline. The following errors have occurred:

Command failed with exit code 1: tsc --build


    at makeError (/Users/michaelkantor/Documents/interweave/node_modules/@boost/core/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/Users/michaelkantor/Documents/interweave/node_modules/@boost/core/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by milesj** [comment]
Unfortunately `mkantor@gmail.com?` is a valid URL, as it's merely a shorthand for `http://mkantor@gmail.com?`. The `mkantor@` is the "auth" while `?` is an empty query string.

Let me think about this a bit more.

**Comment by daria-github** [comment]
Any update on this issue? Running into this as well.
