### ISSUE TITLE
Unable to run tests locally, missing `interweave-emoji`

### ISSUE THREAD

**Issue by tommymarshall** [milesj/interweave#204]
### Description
Wanted to contribute to the project by adding additional matches and enhancements, struggling to get tests running:

### Output
```bash
➜  interweave git:(master) yarn test
yarn run v1.22.10
$ yarn run type
$ beemo typescript --reference-workspaces --build
[1/2] CONFIG Creating config files
[2/2] DRIVER Running TypeScript v4.1.5 driver

🤖  Powered by Beemo v1.1.8
$ yarn run jest
$ beemo jest
[1/2] CONFIG Creating config files
[2/2] DRIVER Running Jest v26.6.3 driver (failed)

 FAIL  packages/emoji/tests/EmojiMatcher.test.tsx
  ● Test suite failed to run

    Cannot find module 'interweave-emoji' from 'tests/setup.ts'

      1 | import { loadEmojiData, loadMeta, loadShortcodes } from 'emojibase-test-utils';
    > 2 | import { EmojiDataManager } from 'interweave-emoji';
        | ^
      3 | import EmojiDataSourceManager from '../packages/emoji/src/EmojiDataManager';
      4 |
      5 | const data = loadEmojiData([loadShortcodes()]);

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (tests/setup.ts:2:1)

// ... lots of failing tests

Test Suites: 29 failed, 29 total
Tests:       0 total
Snapshots:   0 total
Time:        6.6 s
Ran all test suites.

Failed to execute pipeline. The following errors have occurred:

Command failed with exit code 1: jest --colors --logHeapUsage


    at makeError (/Users/tommymarshall/Personal/Code/interweave/node_modules/@boost/core/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/Users/tommymarshall/Personal/Code/interweave/node_modules/@boost/core/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I installed `interweave-emoji` emoji in the project and globally successfully, but these tests still can't find it.

### Solution / Workaround
None that I can see. Might be as simple as updating docs for contributing.

### Versions Used
* node v14.17.3
* yarn 1.22.10

**Comment by milesj** [comment]
@tommymarshall `yarn install && yarn build` is all that should be required.

**Comment by tommymarshall** [comment]
Thanks! Closing.
