### ISSUE TITLE
RefernceError: document is not defined 

### ISSUE THREAD

**Issue by binarygrrl** [milesj/interweave#66]
I'm getting an error when trying to run a simple Hello World example: 
import Interweave from 'interweave';

....in render method
Interweave content="Hello World" (gt and lt omitted to show)

Error:
ReferenceError: document is not defined
    at Parser.createDocument (/usr/src/app/node_modules/interweave/lib/Parser.js:201:15)
    at new Parser (/usr/src/app/node_modules/interweave/lib/Parser.js:70:21)
    at Interweave.parseMarkup (/usr/src/app/node_modules/interweave/lib/Interweave.js:70:18)
    at Interweave.render (/usr/src/app/node_modules/interweave/lib/Interweave.js:97:27)
    at processChild (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2863:18)
    at resolve (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2716:5)
    at ReactDOMServerRenderer.render (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3100:22)
    at ReactDOMServerRenderer.read (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
    at ReactMarkupReadableStream._read (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3578:38)
    at ReactMarkupReadableStream.Readable.read (_stream_readable.js:453:10)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Is there a fix?

**Comment by milesj** [comment]
@binarygrrl This looks like server side rendering? It requires a DOM. https://milesj.gitbook.io/interweave/ssr
