### ISSUE TITLE
Interweave v12

### ISSUE THREAD

**Issue by milesj** [milesj/interweave#80]
Now the emojis are being released in new OS versions, like Android 10, I can start looking into the next major.

- [x] Upgrade to `emojibase` v3.
- [x] Support new emojis in emoji picker.
- [x] Switch from `react-virtualized` to `react-window`.
- [x] Add matcher interleaving.
- [x] Add new SSR package.
- [x] Switch tests to `rut`.
- [x] Switch to hooks and remove HOCs.
- [x] Rename white/black to allow/block in emoji picker.
- [x] Utilize new context more.

**Comment by zaguiini** [comment]
I'd like a prop to specify a custom `document` instance, for usage in places like SSR for example. My app crashes currently:

```
{
    "name": "ReferenceError",
    "message": "document is not defined",
    "stack": "ReferenceError: document is not defined
        at Parser.createDocument (/home/confidential/node_modules/interweave/lib/Parser.js:202:15)
        at new Parser (/home/confidential/node_modules/interweave/lib/Parser.js:71:21)
        at Interweave.parseMarkup (/home/confidential/node_modules/interweave/lib/Interweave.js:70:18)
        at Interweave.render (/home/confidential/node_modules/interweave/lib/Interweave.js:97:27)
        at processChild (/home/confidential/node_modules/react-dom/cjs/react-dom-server.node.development.js:2959:18)
        at resolve (/home/confidential/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
        at ReactDOMServerRenderer.render (/home/confidential/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
        at ReactDOMServerRenderer.read (/home/confidential/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
        at renderToString (/home/confidential/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
        at Module.reactRender (webpack:///./src/server/serverUtils.jsx?:323:255)
        at eval (webpack:///./src/server/index.js?:197:75)
        at tracer.scope.activate (/home/confidential/node_modules/dd-trace/packages/dd-trace/src/plugins/util/promise.js:28:23)
        at Scope._activate (/home/confidential/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:44:14)
        at Scope.activate (/home/confidential/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:13:17)
        at /home/confidential/node_modules/dd-trace/packages/dd-trace/src/plugins/util/promise.js:27:27
        at tryCatcher (/home/confidential/node_modules/bluebird/js/release/util.js:16:23)"
}
```

**Comment by milesj** [comment]
@zaguiini I'm working on a new SSR package but in the mean time, you can bootstrap JSDOM. https://milesj.gitbook.io/interweave/ssr
